In [1]:
import numpy as np
    

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-0.24714213, -0.48681793,  0.48850189, -0.39991818,  0.3705206 ,
        1.26419245,  0.31399668,  0.57534855, -0.85150499, -1.913041  ])

In [7]:
B = np.random.randn(10)
B

array([ 0.57805797, -1.22184237, -1.09789187, -0.80950192,  0.1907825 ,
        1.7078258 , -0.02717228,  0.21799892,  0.45164005, -0.66734744])

In [8]:
# Binary Funcitons
np.add(A,B)

array([ 0.33091584, -1.70866029, -0.60938998, -1.2094201 ,  0.5613031 ,
        2.97201825,  0.2868244 ,  0.79334747, -0.39986494, -2.58038844])

In [9]:
np.maximum(A,B)

array([ 0.57805797, -0.48681793,  0.48850189, -0.39991818,  0.3705206 ,
        1.7078258 ,  0.31399668,  0.57534855,  0.45164005, -0.66734744])

In [10]:
np.minimum(A,B)

array([-0.24714213, -1.22184237, -1.09789187, -0.80950192,  0.1907825 ,
        1.26419245, -0.02717228,  0.21799892, -0.85150499, -1.913041  ])

In [11]:
website = 'http://www.amazon.com/Philips-HF3520-Wake-Up-Colored-Simulation/dp/B0093162RM/ref=cm_cr_pr_product_top?ie=UTF8'
import webbrowser
webbrowser.open(website)

True