In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2],index=['T','U','V'])

In [8]:
ser2 = Series([3,4],index=['X','Y'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1,ser2],axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0  1.308892 -0.859021 -1.573951
1 -0.095476 -1.083241 -0.347507
2  0.503770 -0.826078  2.021676
3  0.161179  1.281658  0.603105

In [16]:
dframe2

Y         Q         X
0  0.750198 -0.832816  1.124330
1 -0.667360  0.521001 -0.422537
2  0.813803 -1.236305  1.311618

In [17]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN  1.308892 -0.859021 -1.573951
1       NaN -0.095476 -1.083241 -0.347507
2       NaN  0.503770 -0.826078  2.021676
3       NaN  0.161179  1.281658  0.603105
0 -0.832816  1.124330  0.750198       NaN
1  0.521001 -0.422537 -0.667360       NaN
2 -1.236305  1.311618  0.813803       NaN

In [18]:
# index was ingored 
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN  1.308892 -0.859021 -1.573951
1       NaN -0.095476 -1.083241 -0.347507
2       NaN  0.503770 -0.826078  2.021676
3       NaN  0.161179  1.281658  0.603105
4 -0.832816  1.124330  0.750198       NaN
5  0.521001 -0.422537 -0.667360       NaN
6 -1.236305  1.311618  0.813803       NaN